### ISSUE TITLE
TO:DO List

### ISSUE THREAD

**Issue by OnlineRepz** [AlexFreedomRemake/AlexFreedomMod-Revamped#15]
- [ ] Donator System API
- [x] Revamp the rank system
- [x] Fix the banning system
- [x] Revamp Telnet

**Comment by Verdon-Online** [comment]
@AlexFreedomRemake/alexfreedom, this API is taking longer than I expected. Please hold tight as I am currently doing API tweaking.

Thank you for your understanding.

**Comment by Verdon-Online** [comment]
I am currently making new repo for Donator System plugin to make compatible with FOPM;R, if not, I will change this over to TFM. I am currently coding my Free-Op plugin. The reason I am coding is because I am trying to make it more flexible. Making it stronger by using TFM and FOPM;R. But with my coding.

**Comment by AlphaGaming** [comment]
Updated

**Comment by AlphaGaming** [comment]
We need to edit the Donator API still

**Comment by AlexFreedomMod** [comment]
Yes, but I would like to get the server up before Dec. 25 (Christmas) and since it would take a while why don't we just out it on hold or we could try to get out the release with the Donor API fixed and get it on a server A.S.A.P

**Comment by AlphaGaming** [comment]
Alex I want to start the server on New Year day

**Comment by OnlineRepz** [comment]
Issue Closed

**Comment by OnlineRepz** [comment]
See Issue #17

**Comment by AlexFreedomMod** [comment]
Ok we can do that right?
